name: First-Workflow
on: [push]

jobs:
  run-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run Lint
        run: npm run lint

